/* Automatically @generated by tree-sitter v0.25.4 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 25
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 19
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_definition = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_relation = 4,
  anon_sym_COLON = 5,
  anon_sym_permission = 6,
  anon_sym_EQ = 7,
  anon_sym_DOT = 8,
  sym_identifier = 9,
  sym_source_file = 10,
  sym_definition = 11,
  sym_statement = 12,
  sym_relation = 13,
  sym_permission = 14,
  sym_type = 15,
  sym_expression = 16,
  aux_sym_source_file_repeat1 = 17,
  aux_sym_definition_repeat1 = 18,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_definition] = "definition",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_relation] = "relation",
  [anon_sym_COLON] = ":",
  [anon_sym_permission] = "permission",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT] = ".",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym_definition] = "definition",
  [sym_statement] = "statement",
  [sym_relation] = "relation",
  [sym_permission] = "permission",
  [sym_type] = "type",
  [sym_expression] = "expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_definition_repeat1] = "definition_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_definition] = anon_sym_definition,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_relation] = anon_sym_relation,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_permission] = anon_sym_permission,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym_definition] = sym_definition,
  [sym_statement] = sym_statement,
  [sym_relation] = sym_relation,
  [sym_permission] = sym_permission,
  [sym_type] = sym_type,
  [sym_expression] = sym_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_definition_repeat1] = aux_sym_definition_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_definition] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_relation] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_permission] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_relation] = {
    .visible = true,
    .named = true,
  },
  [sym_permission] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(27);
      ADVANCE_MAP(
        '.', 35,
        ':', 32,
        '=', 34,
        'd', 2,
        'p', 3,
        'r', 4,
        '{', 29,
        '}', 30,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == 'f') ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 8:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(1);
      END_STATE();
    case 13:
      if (lookahead == 'm') ADVANCE(7);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(33);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 26:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_definition);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_relation);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_permission);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 26},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 26},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 26},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 26},
  [21] = {.lex_state = 26},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 26},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_definition] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_relation] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_permission] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(19),
    [sym_definition] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_definition] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(7), 1,
      anon_sym_RBRACE,
    ACTIONS(9), 1,
      anon_sym_relation,
    ACTIONS(11), 1,
      anon_sym_permission,
    STATE(3), 2,
      sym_statement,
      aux_sym_definition_repeat1,
    STATE(8), 2,
      sym_relation,
      sym_permission,
  [18] = 5,
    ACTIONS(9), 1,
      anon_sym_relation,
    ACTIONS(11), 1,
      anon_sym_permission,
    ACTIONS(13), 1,
      anon_sym_RBRACE,
    STATE(4), 2,
      sym_statement,
      aux_sym_definition_repeat1,
    STATE(8), 2,
      sym_relation,
      sym_permission,
  [36] = 5,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 1,
      anon_sym_relation,
    ACTIONS(20), 1,
      anon_sym_permission,
    STATE(4), 2,
      sym_statement,
      aux_sym_definition_repeat1,
    STATE(8), 2,
      sym_relation,
      sym_permission,
  [54] = 3,
    ACTIONS(5), 1,
      anon_sym_definition,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(6), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
  [65] = 3,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_definition,
    STATE(6), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
  [76] = 2,
    ACTIONS(32), 1,
      anon_sym_DOT,
    ACTIONS(30), 3,
      anon_sym_RBRACE,
      anon_sym_relation,
      anon_sym_permission,
  [85] = 1,
    ACTIONS(34), 3,
      anon_sym_RBRACE,
      anon_sym_relation,
      anon_sym_permission,
  [91] = 1,
    ACTIONS(36), 3,
      anon_sym_RBRACE,
      anon_sym_relation,
      anon_sym_permission,
  [97] = 1,
    ACTIONS(38), 3,
      anon_sym_RBRACE,
      anon_sym_relation,
      anon_sym_permission,
  [103] = 1,
    ACTIONS(40), 3,
      anon_sym_RBRACE,
      anon_sym_relation,
      anon_sym_permission,
  [109] = 1,
    ACTIONS(42), 3,
      anon_sym_RBRACE,
      anon_sym_relation,
      anon_sym_permission,
  [115] = 1,
    ACTIONS(44), 2,
      ts_builtin_sym_end,
      anon_sym_definition,
  [120] = 2,
    ACTIONS(46), 1,
      sym_identifier,
    STATE(11), 1,
      sym_type,
  [127] = 1,
    ACTIONS(48), 2,
      ts_builtin_sym_end,
      anon_sym_definition,
  [132] = 2,
    ACTIONS(50), 1,
      sym_identifier,
    STATE(10), 1,
      sym_expression,
  [139] = 1,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
  [143] = 1,
    ACTIONS(54), 1,
      sym_identifier,
  [147] = 1,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
  [151] = 1,
    ACTIONS(58), 1,
      sym_identifier,
  [155] = 1,
    ACTIONS(60), 1,
      sym_identifier,
  [159] = 1,
    ACTIONS(62), 1,
      anon_sym_EQ,
  [163] = 1,
    ACTIONS(64), 1,
      anon_sym_COLON,
  [167] = 1,
    ACTIONS(66), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 18,
  [SMALL_STATE(4)] = 36,
  [SMALL_STATE(5)] = 54,
  [SMALL_STATE(6)] = 65,
  [SMALL_STATE(7)] = 76,
  [SMALL_STATE(8)] = 85,
  [SMALL_STATE(9)] = 91,
  [SMALL_STATE(10)] = 97,
  [SMALL_STATE(11)] = 103,
  [SMALL_STATE(12)] = 109,
  [SMALL_STATE(13)] = 115,
  [SMALL_STATE(14)] = 120,
  [SMALL_STATE(15)] = 127,
  [SMALL_STATE(16)] = 132,
  [SMALL_STATE(17)] = 139,
  [SMALL_STATE(18)] = 143,
  [SMALL_STATE(19)] = 147,
  [SMALL_STATE(20)] = 151,
  [SMALL_STATE(21)] = 155,
  [SMALL_STATE(22)] = 159,
  [SMALL_STATE(23)] = 163,
  [SMALL_STATE(24)] = 167,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_definition_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_permission, 4, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relation, 4, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 4, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 5, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [56] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_authzed(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
